# Rename columns to db format/names
product_schema = {
    'ID': 'product_id',
    'Source?': 'source',
    'Product Name - Preferred': 'preferred_name',
    'Product Name - Chemical': 'chemical_name',
    'Product Name - Brand': 'brand_name',
    'Sponsor': 'sponsors',
    'Intervention Type': 'intervention_type',
    'Indication': 'indication',
    'Molecule Type': 'molecule_type',
    'Therapeutic Approach': 'therapeutic_approach',
    'New/Repurposed': 'repurposed',
    'Notes': 'notes',
    'Funding/Manufacturing/Research/Other Partners': 'other_partners',
    'Country': 'countries',
    'Current Stage': 'current_stage',
    'Pre-Clinical Studies Started': 'pre_clinical_studies_started_date',
    'Lead Selection Finalized': 'lead_selection_finalized_date',
    'Clinical Batch Finalized': 'clinical_batch_finalized_date',
    'IND or Equivalent Approval Finalized': 'ind_finalized_date',
    'Phase 1 Started': 'phase_1_started_date',
    'Phase 2 Started': 'phase_2_started_date',
    'Phase 3 Started': 'phase_3_started_date',
    'NDA or equivalent Approval Finalized': 'nda_finalized',
    'Phase': 'phase',
    'Condition or Disease': 'condition_or_disease',
    'Number of Participants': 'number_participants',
    'Accepts Healthy Subjects': 'accepts_healthy_subjects',
    '# of Sites': 'num_sites',
    'Sites Locations': 'site_locations',
    'Study Start Date': 'study_start_date',
    'Primary Completion DAte': 'primary_completion_date',
    'Study Completion Date': 'study_completion_date',
    'How to participate': 'participation_link',
    'Discovery Started': 'discovery_started_date',
    'CTG Identifier': 'trial_id',
    'Status': 'status',
}